apiVersion: v1
kind: Service
metadata:
  name: {{ include "skyloud.fullname" . }}
  labels:
    {{- include "skyloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.exposePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "skyloud.selectorLabels" . | nindent 4 }}
